run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck    # 检查未处理的错误
    - gosimple    # 检查是否可以简化代码
    - govet       # 官方静态分析
    - ineffassign # 检查无效赋值
    - staticcheck # 高级静态分析
    - typecheck
    - unused      # 检查未使用的代码
    - gofmt       # 强制格式化

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

version: 1
